// scripts/destfest-queries.mjs
// Query Wikimedia Commons untuk gambar destinasi wisata & festival.
// key = nama file lokal (tanpa .jpg), value = kata kunci pencarian.

export const DEST_FEST_QUERIES = {
  // ===== DESTINASI =====
  "tsunami-museum": "Aceh Tsunami Museum Banda Aceh",
  "gunung-leuser": "Gunung Leuser National Park Sumatra",
  "pantai-iboh": "Sabang island beach",
  "danau-toba-samosir": "Lake Toba Samosir",
  "istana-maimun": "Istana Maimun Medan",
  "bukit-holbung": "Berastagi Karo",
  "jam-gadang": "Jam Gadang Bukittinggi",
  "nagari-pariangan": "Pariangan village",
  "lembah-harau": "Harau Valley",
  "muara-takus": "Muara Takus temple",
  "istana-siak": "Siak Sri Indrapura palace",
  "masjid-an-nur": "An-Nur Great Mosque Pekanbaru",
  "muaro-jambi": "Muaro Jambi temple",
  "gunung-tujuh": "Lake Gunung Tujuh Kerinci",
  "gentala-arasy": "Gentala Arasy Jambi",
  "ampera": "Ampera Bridge Palembang",
  "gunung-dempo": "Mount Dempo Pagar Alam",
  "danau-ranau": "Lake Ranau South Sumatra",
  "benteng-marlborough": "Fort Marlborough Bengkulu",
  "rafflesia": "Rafflesia arnoldii",
  "pulau-enggano": "Enggano island",
  "way-kambas": "Way Kambas elephant",
  "pahawang": "Pahawang island Lampung",
  "menara-siger": "Bakauheni Lampung",
  "tanjung-tinggi": "Tanjung Tinggi beach Belitung",
  "museum-kata": "Museum Kata Andrea Hirata",
  "pasir-padi": "Pasir Padi beach Pangkalpinang",
  "pulau-penyengat": "Penyengat island Tanjungpinang",
  "jembatan-barelang": "Barelang bridge Batam",
  "busung-bintan": "Bintan island beach",

  "ujung-kulon": "Ujung Kulon national park",
  "banten-lama": "Masjid Agung Banten",
  "pantai-sawarna": "Sawarna beach",
  "halimun-salak": "Mount Halimun Salak",
  "monas": "Monumen Nasional",
  "kota-tua": "Kota Tua Jakarta",
  "tmii": "Taman Mini Indonesia Indah",
  "ragunan": "Ragunan zoo",
  "tangkuban-parahu": "Tangkuban Perahu crater",
  "kampung-naga": "Kampung Naga",
  "kawah-putih": "Kawah Putih Ciwidey",
  "keraton-kasepuhan": "Keraton Kasepuhan Cirebon",
  "borobudur": "Borobudur temple",
  "dieng": "Dieng plateau Telaga Warna",
  "lawang-sewu": "Lawang Sewu Semarang",
  "keraton-surakarta": "Keraton Surakarta",
  "prambanan": "Prambanan temple",
  "malioboro": "Malioboro street",
  "parangtritis": "Parangtritis beach",
  "goa-jomblang": "Jomblang cave",
  "bromo": "Mount Bromo",
  "kawah-ijen": "Kawah Ijen blue fire",
  "museum-angkut": "Museum Angkut Batu",
  "pulau-merah": "Red island beach Banyuwangi",

  "tanah-lot": "Tanah Lot temple",
  "ubud-monkey-forest": "Ubud monkey forest",
  "uluwatu": "Uluwatu temple",
  "penglipuran": "Penglipuran village",
  "gunung-batur": "Mount Batur Kintamani",
  "rinjani": "Mount Rinjani Segara Anak",
  "gili-trawangan": "Gili Trawangan",
  "pringgasela": "Lombok weaving",
  "pantai-lawata": "Bima West Nusa Tenggara",
  "kuta-mandalika": "Kuta Mandalika beach",
  "komodo": "Komodo national park",
  "kelimutu": "Kelimutu lake",
  "desa-adat-bena": "Bena village Ngada",
  "walakiri": "Walakiri beach Sumba",
  "wae-rebo": "Wae Rebo village",

  "betung-kerihun": "Betung Kerihun national park",
  "tugu-khatulistiwa": "Equator monument Pontianak",
  "pasir-panjang-singkawang": "Singkawang beach",
  "tanjung-puting": "Tanjung Puting orangutan",
  "sebangau": "Sebangau national park",
  "danau-sembuliat": "Central Kalimantan lake",
  "pasar-terapung-lok-baintan": "Lok Baintan floating market",
  "loksado": "Loksado bamboo rafting",
  "menara-pandang-banjarmasin": "Banjarmasin Martapura river",
  "derawan": "Derawan island",
  "desa-pampang": "Pampang Dayak village",
  "manggar-segarasari": "Manggar beach Balikpapan",
  "pantai-amal-tarakan": "Tarakan beach",
  "kayan-mentarang": "Kayan Mentarang national park",
  "semolon": "Kalimantan Utara waterfall",

  "bunaken": "Bunaken national park",
  "danau-tondano": "Lake Tondano",
  "tomohon-flowers": "Tomohon flower",
  "benteng-otanaha": "Otanaha fortress Gorontalo",
  "danau-limboto": "Lake Limboto",
  "saronde": "Saronde island Gorontalo",
  "lore-lindu": "Lore Lindu megalith",
  "togean": "Togean island",
  "danau-poso": "Lake Poso Tentena",
  "manakarra": "Manakarra beach Mamuju",
  "dato-majene": "Majene beach",
  "mamasa": "Mamasa traditional house",
  "kete-kesu": "Kete Kesu Tongkonan Toraja",
  "losari": "Losari beach Makassar",
  "rammang-rammang": "Rammang Rammang Maros",
  "wakatobi": "Wakatobi coral",
  "benteng-buton": "Buton palace fortress Baubau",
  "labengki": "Labengki island",

  "natsepa": "Natsepa beach Ambon",
  "ngurbloat": "Ngurbloat beach Kei",
  "benteng-tolukko": "Fort Tolukko Ternate",
  "pulau-maitara": "Maitara island",
  "danau-sentani": "Lake Sentani",
  "pantai-hamadi": "Jayapura beach",
  "teluk-cenderawasih": "Cenderawasih Bay",
  "pegunungan-arfak": "Arfak mountains",
  "wayag": "Wayag Raja Ampat",
  "pagoda-sapta-ratna": "Sorong city",
  "wasur": "Wasur national park Merauke",
  "rawa-biru-asmat": "Asmat Papua",
  "lorentz": "Lorentz national park",
  "danau-paniai": "Paniai lake",
  "lembah-baliem": "Baliem valley Wamena",
  "gua-kontilola": "Papua cave painting",

  // ===== FESTIVAL =====
  "tabuik-pariaman": "Tabuik Pariaman",
  "pacu-jalur-fest": "Pacu Jalur Riau",
  "festival-danau-toba": "Lake Toba",
  "tabut-bengkulu": "Tabot Bengkulu festival",
  "festival-sriwijaya": "Palembang Sriwijaya",
  "cap-go-meh-bogor": "Cap Go Meh Bogor",
  "reog-ponorogo-fest": "Reog Ponorogo",
  "jember-fashion": "Jember Fashion Carnaval",
  "dieng-culture-fest": "Dieng Culture Festival",
  "wjnc": "Yogyakarta wayang",
  "gandrung-sewu": "Gandrung Banyuwangi",
  "seba-baduy-fest": "Baduy Seba",
  "pesta-kesenian-bali": "Pesta Kesenian Bali",
  "pasola-kodi": "Pasola Sumba",
  "bau-nyale": "Bau Nyale Lombok",
  "rimpu-mantika": "Rimpu Bima",
  "alunan-pringgasela": "Sasak traditional weaving",
  "gili-festival": "Gili Trawangan",
  "mulud-adat-bayan": "Bayan Beleq mosque",
  "pekan-gawai-dayak": "Gawai Dayak Pontianak",
  "isen-mulang": "Isen Mulang Palangka Raya",
  "bamboo-rafting-loksado": "Loksado bamboo rafting",
  "abutta-banua": "Berau East Kalimantan",
  "iraw-tengkayu": "Tarakan North Kalimantan",
  "tiff": "Tomohon flower festival",
  "karnaval-karawo": "Gorontalo sulaman",
  "festival-danau-poso": "Tentena Lake Poso",
  "toraya-magellu": "Toraja dance",
  "wakatobi-wave": "Wakatobi WAVE",
  "uta-dada": "Sigi Central Sulawesi",
  "festival-tidore": "Tidore island",
  "festival-danau-sentani": "Sentani festival Papua",
  "lembah-baliem-fest": "Baliem Valley festival",
  "pesona-meti-kei": "Kei islands Maluku",
  "banda-neira-fest": "Banda Neira",
}
