// scripts/image-queries.mjs
// Query pencarian Wikimedia Commons per file target.
// key = nama file lokal (tanpa .jpg), value = kata kunci pencarian gambar.
// Nilai sudah diperbaiki untuk item yang gagal temuan pertama (query lebih umum).
export const IMAGE_QUERIES = {
  "aceh-mie-aceh": "Mie Aceh",
  "aceh-tari-saman": "Tari Saman",
  "aceh-kenduri-laut": "piala laot Aceh",
  "aceh-rencong": "Rencong Aceh",
  "sumut-arsik": "Arsik ikan mas",
  "sumut-tor-tor": "Tari Tor Tor Batak",
  "sumut-mangalahat-horbo": "Kerbau Batak",
  "sumut-ulos": "Ulos Batak",
  "sumbar-rendang": "Rendang",
  "sumbar-tari-piring": "Tari Piring",
  "sumbar-makan-bajamba": "Makan bajamba",
  "sumbar-songket-silungkang": "Songket Silungkang",
  "riau-gulai-belacan": "Udang belacan",
  "riau-tari-zapin": "Tari Zapin",
  "riau-pacu-jalur": "Pacu jalur",
  "riau-tenun-siak": "Tenun Riau",
  "kepri-gonggong": "Gonggong",
  "kepri-tari-persembahan": "Tari persembahan Melayu",
  "kepri-mandi-safar": "Mandi Safar",
  "kepri-tepak-sirih": "Tepak sirih",
  "jambi-tempoyak": "Tempoyak ikan patin",
  "jambi-tari-sekapur-sirih": "Tari Sekapur Sirih",
  "jambi-kenduri-sko": "Kenduri Sko Kerinci",
  "jambi-batik-angso-duo": "Batik Jambi",
  "sumsel-pempek": "Pempek Palembang",
  "sumsel-gending-sriwijaya": "Tari Gending Sriwijaya",
  "sumsel-sedekah-rame": "Pasemah Lahat",
  "sumsel-songket-palembang": "Songket Palembang",
  "bengkulu-pendap": "Pendap Bengkulu",
  "bengkulu-tari-tabot": "Tabot",
  "bengkulu-upacara-tabut": "Tabot Bengkulu",
  "bengkulu-batik-besurek": "Batik Besurek",
  "lampung-seruit": "Seruit Lampung",
  "lampung-tari-sigeh-pengaten": "Tari Sigeh Penguten Lampung",
  "lampung-begawi": "Lampung Pepadun",
  "lampung-kain-tapis": "Kain Tapis Lampung",
  "babel-lempah-kuning": "Lempah kuning Bangka",
  "babel-tari-sepen": "dance Belitung Indonesia",
  "babel-nganggung": "Bangka Belitung",
  "babel-kopiah-resam": "Bangka island",

  "banten-sate-bandeng": "Sate Bandeng",
  "banten-tari-cokek": "Tari Cokek",
  "banten-seba-baduy": "Seba Baduy",
  "banten-batik-banten": "Batik Banten",
  "jakarta-kerak-telor": "Kerak telor",
  "jakarta-tari-yapong": "Tari Yapong",
  "jakarta-roti-buaya": "Roti buaya",
  "jakarta-ondel-ondel": "Ondel ondel",
  "jabar-nasi-timbel": "Nasi timbel",
  "jabar-tari-jaipong": "Tari Jaipong",
  "jabar-seren-taun": "Seren Taun",
  "jabar-angklung": "Angklung",
  "jateng-lumpia-semarang": "Lumpia Semarang",
  "jateng-tari-gambyong": "Tari Gambyong",
  "jateng-ruwatan-rambut-gimbal": "Rambut gimbal Dieng",
  "jateng-ukir-jepara": "Ukiran Jepara",
  "diy-gudeg": "Gudeg",
  "diy-bedhaya-ketawang": "Tari Bedhaya",
  "diy-grebeg-maulud": "Grebeg Maulud",
  "diy-perak-kotagede": "Perak Kotagede",
  "jatim-rawon": "Rawon",
  "jatim-tari-gandrung": "Tari Gandrung Banyuwangi",
  "jatim-yadnya-kasada": "Yadnya Kasada Bromo",
  "jatim-reog-ponorogo": "Reog Ponorogo",

  "bali-ayam-betutu": "Ayam betutu",
  "bali-tari-kecak": "Tari Kecak",
  "bali-ngaben": "Ngaben Bali",
  "bali-kain-gringsing": "Geringsing Bali",
  "ntb-ayam-taliwang": "Ayam Taliwang",
  "ntb-tari-gandrung": "Gandrung Lombok",
  "ntb-bau-nyale": "Bau Nyale",
  "ntb-songket-sasak": "Songket Sasak Lombok",
  "ntt-daging-sei": "Se'i Kupang",
  "ntt-tari-caci": "Tari Caci Flores",
  "ntt-pasola": "Pasola Sumba",
  "ntt-tenun-ikat": "Tenun ikat Sumba",

  "kalbar-bubur-pedas": "Bubur pedas Sambas",
  "kalbar-tari-monang": "Tari Dayak",
  "kalbar-ngongkong": "Rumah Betang Dayak",
  "kalbar-tenun-ikat-dayak": "Tenun ikat Dayak",
  "kalteng-juhu-singkah": "Makanan Dayak",
  "kalteng-tari-giring-giring": "Tari Giring Giring",
  "kalteng-tiwah": "Tiwah Dayak",
  "kalteng-anyaman-anjat": "Anjat Dayak",
  "kalsel-soto-banjar": "Soto Banjar",
  "kalsel-tari-baksa-kembang": "Tari Baksa Kembang",
  "kalsel-baayun-maulid": "Baayun Maulid",
  "kalsel-kain-sasirangan": "Sasirangan",
  "kaltim-nasi-kuning-samarinda": "Nasi kuning Samarinda",
  "kaltim-tari-gong": "Tari Dayak Kenyah",
  "kaltim-erau": "Erau Kutai",
  "kaltim-tenun-samarinda": "Tenun Samarinda",
  "kaltara-sate-terap": "Bulungan Kalimantan",
  "kaltara-tari-lalaya": "Tari Dayak Kalimantan",
  "kaltara-iraw-tengkayu": "Tarakan",
  "kaltara-manik-dayak": "Manik Dayak",

  "sulut-tinutuan": "Tinutuan bubur Manado",
  "sulut-tari-maengket": "Tari Maengket",
  "sulut-tulude": "Sangihe Talaud",
  "sulut-kain-bentenan": "Tenun Bentenan",
  "gorontalo-binte-biluhuta": "Binte biluhuta",
  "gorontalo-tari-polopalo": "Tari Gorontalo",
  "gorontalo-tumbilotohe": "Tumbilotohe Gorontalo",
  "gorontalo-sulam-karawo": "Karawo Gorontalo",
  "sulteng-kaledo": "Kaledo Palu",
  "sulteng-tari-dero": "Tari Poso",
  "sulteng-padungku": "Padungku",
  "sulteng-kain-fuya": "Barkcloth",
  "sulbar-jepa": "Mandar Sulawesi Barat",
  "sulbar-sayyang-pattudu": "Mandar tradition horse",
  "sulbar-mappandoe-tolo": "Tradisi Mandar",
  "sulbar-sutra-saqbe": "Tenun Mandar",
  "sulsel-coto-makassar": "Coto Makassar",
  "sulsel-tari-pakarena": "Tari Pakarena",
  "sulsel-rambu-solo": "Rambu Solo Toraja",
  "sulsel-perahu-pinisi": "Pinisi perahu",
  "sultra-sinonggi": "Tolaki Kendari",
  "sultra-tari-lulo": "Tari Lulo",
  "sultra-upacara-karia": "Suku Muna",
  "sultra-tenun-buton": "Tenun Buton",

  "maluku-nasi-lapola": "Makanan Maluku",
  "maluku-tari-cakalele": "Tari Cakalele",
  "maluku-pela-gandong": "Pela Gandong",
  "maluku-kerajinan-kerang": "Ambon shell craft",
  "malut-gohu-ikan": "Gohu ikan Ternate",
  "malut-tari-soya-soya": "Tari Ternate",
  "malut-kololi-kie": "Gamalama Ternate",
  "malut-batik-tubo": "Batik Ternate",
  "papua-papeda": "Papeda sagu",
  "papua-tari-yospan": "Tari Yospan",
  "papua-wor": "Suku Biak Papua",
  "papua-lukisan-kulit-kayu": "Sentani painting",
  "pabar-sagu-sep": "Sagu Papua Barat",
  "pabar-tari-tumbu-tanah": "Tari Arfak",
  "pabar-igya-seranjob": "Suku Arfak",
  "pabar-manik-arfak": "Suku Arfak Papua",
  "pabarda-udang-selingkuh": "Udang selingkuh",
  "pabarda-tari-gale-gale": "Tari Sorong",
  "pabarda-sasi-laut": "Raja Ampat sasi",
  "pabarda-anyaman-topi-saya": "Raja Ampat",
  "pasel-sagu-lempeng": "Sagu lempeng",
  "pasel-tari-telsain": "Merauke",
  "pasel-bisj-asmat": "Asmat bisj",
  "pasel-ukiran-asmat": "Asmat carving",
  "pateng-olahan-keladi": "Keladi Papua",
  "pateng-tari-aniri": "Suku Kamoro",
  "pateng-karapao": "Kamoro Mimika",
  "pateng-ukiran-yamane": "Kamoro carving",
  "pagu-ubi-jalar-bakar-batu": "Bakar batu Papua",
  "pagu-tari-perang-dani": "Dani war dance Baliem",
  "pagu-bakar-batu": "Papua bakar batu",
  "pagu-noken-pikon": "Noken Papua",
}